Add skipLibCheck parameter because of react-toastify.
If skipLibCheck is false, "tsc" is fired on librairies and it fails because a class ToastContainer is not present in react-toastify.

$ yarn tsc
node_modules/react-toastify/dist/components/index.d.ts:3:15 - error TS2307: Cannot find module './ToastContainer' or its corresponding type declarations.

Issue related: https://github.com/fkhadra/react-toastify/issues/561